management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics

spring:
  elasticsearch:
    uris: http://elasticsearch:9200
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
  data:
    mongodb:
      host: mongo
      port: 27017
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: test_db